### ISSUE TITLE
Rename to ImageEditor

### ISSUE THREAD

**Issue by rollsroyc3** [wwimmo/react-native-sketch-canvas#2]
Hey and thanks for keeping this repo updated!

I ran into an issue while building my iOS app for production with this fork. The error is 

❌  ld: library not found for -lRNImageEditor
❌  clang: error: 

Im guessing it might have something to do with renaming the repo to ImageEditor, but not sure how to go about fixing it. Let me know if theres anything I can do!

**Comment by creambyemute** [comment]
@rollsroyc3 Yeah that's because of the renaming. I did that because I'm using the original repository library for signature and this one for image editing.

I'm afraid rn-link might not work (haven't tested yet).
Podspec may also not work (haven't tested yet), so you are best off linking it manually.

1. Remove old linking (RNSketchCanvas)
1.1 Android: settings.gradle, app/build.gradle (dependencies section) and MainApplication.java
1.2 iOS: Remove .xcodeproj (if manually linked) from libraries, Remove library from targets

2. Add new linking (RNImageEditor)
2.1 Android: settings.gradle, app/build.gradle (dependencies section) and MainApplication.java
2.2 iOS: Add .xcodeproj (if manually linked) to libraries, add library to targets
